build:
    project_setup:
        after:
            - 'composer update'
    tests:
        override:
            -
                command: vendor/bin/codecept run -c tests/
    dependencies:
        before:
            - mysql -uroot -e 'CREATE DATABASE `test-mata-app`'